### ISSUE TITLE
Connect to IFTTT

### ISSUE THREAD

**Issue by elimisteve** [sbhackerspace/PartyMode#21]
Similar to this: https://ifttt.com/recipes/341866-alexa-trigger-party-time

**Comment by gholms** [comment]
We wouldn't want to make it _too_ easy to engage party mode, but perhaps this could be one of several steps in that process.

It could also potentially do the reverse, triggering things as part of party mode itself.

**Comment by mkapuscik** [comment]
@elimisteve All party activation related orders shall be duly verified and carried out exclusively by two members of the hackerspace Strategic Party Commission. Allowing insecure and unverifiable external systems access to any part of the decision making process violates the Hackerspace Command Authority and the Single Integrated Party Plan (S.I.P.P.). The United States has a similar structure that was templated off of ours called the [SIOP](https://en.wikipedia.org/wiki/Single_Integrated_Operational_Plan#Executing the SIOP) if you would like more information.
