### ISSUE TITLE
hdmi cable from pi 2 reciver

### ISSUE THREAD

**Issue by dloman** [sbhackerspace/PartyMode#7]
we should get a cable long enough for this

**Comment by dloman** [comment]
75ft hdmi cables are more expensive then I thought. This could work

http://www.newegg.com/Product/Product.aspx?Item=9SIA1KT0FT6291&cm_re=hdmi_to_ethernet_adapter-_-9SIA1KT0FT6291-_-Product

**Comment by mkapuscik** [comment]
@dloman ordered the cable extender. It was installed and doesn't work.

**Comment by mkapuscik** [comment]
We are using a separate machine for visualization so this is no longer applicable.
