### ISSUE TITLE
Dial on main panel

### ISSUE THREAD

**Issue by dloman** [sbhackerspace/PartyMode#8]
several things to do:
*wire leds
*program leds
*design dial
*print dial

**Comment by dloman** [comment]
got the ring lights working. the current code to control them is super slow. 
Still TODO: 
- make the wiring permanent/ mount the led ring
- write code that isn't slow (this will be easy the code i threw is novelty slow)
- design and print dial

**Comment by sphereinabox** [comment]
There's a new larger dial on there as of yesterday.

**Comment by dloman** [comment]
new one looks rad
